paraula=(input("Introdueix la paraula 1"))
paraula2=(input("Introdueix la paraula 2"))
paraula3=(input("Introdueix la paraula 3"))
paraula4=(input("Introdueix la paraula 4"))
paraula5=(input("Introdueix la paraula 5"))
print(paraula1,",",paraula2,",",paraula3,",",paraula4,",",paraula5)